call plug#begin('~/.vim/bundle')
"Integration ---------------------------------------------"{{{
Plug 'fab-du/vim-sensible'
Plug 'tpope/vim-fugitive'     
Plug 'airblade/vim-gitgutter'
Plug 'benmills/vimux'         
Plug '~/.tmux/plugins/vim-tmux-navigator'
Plug 'junegunn/fzf', { 'dir': '~/.fzf' }
Plug 'tpope/vim-classpath' , { 'for' : 'java'}
Plug 'youjumpiwatch/vim-androidmanifest'
Plug 'vim-scripts/adt.vim', { 'for' : 'java'}
Plug 'jez/vim-superman'

" End Integration -----------------------------------------"}}}

" Code completion ------------------------------------"{{{
Plug 'artur-shaik/vim-javacomplete2'

function! BuildYCM(info)
  " info is a dictionary with 3 fields
  " - name:   name of the plugin
  " - status: 'installed', 'updated', or 'unchanged'
  " - force:  set on PlugInstall! or PlugUpdate!
  if a:info.status == 'installed' || a:info.force
    !npm install -g typescript
    !npm install -g tern
    !sudo ./install.py  --tern-completer --gocode-completer
  endif
endfunction
Plug 'Valloric/YouCompleteMe', { 'do': function('BuildYCM') } | Plug 'rdnetto/YCM-Generator'
Plug 'marijnh/tern_for_vim', {'do' : 'npm install' }

"}}}

" Full Language Support "{{{
Plug 'vim-ruby/vim-ruby'
Plug 'fatih/vim-go'
Plug 'vim-scripts/dbext.vim'
Plug 'Townk/vim-qt'
Plug 'suan/vim-instant-markdown', {'for' : 'markdown', 'do' : 'npm install instant-markdown-d -g'}
Plug 'pangloss/vim-javascript'
Plug 'burnettk/vim-angular'
Plug 'moll/vim-node'
Plug 'tpope/vim-markdown' , {'for' : 'markdown'}
" End Full Language Support "}}}

"Make"{{{
Plug 'thinca/vim-quickrun'
if has('nvim')
    Plug 'benekastah/neomake'
endif 
" End Make"}}}

" Enhance vim built-in Features"{{{
Plug 'sjl/gundo.vim'
Plug 'mbbill/undotree'
Plug 'airblade/vim-rooter'
Plug '907th/vim-auto-save'

" End Enhance vim built-in Features"}}}

" Code Navigation"{{{
Plug 'mileszs/ack.vim', {'on' : 'Ack'}
Plug 'rking/ag.vim', {'on' : 'Ag'}
Plug 'majutsushi/tagbar'
" End Code Navigation"}}}

" Vanity stuff"{{{

if !has('nvim')
	Plug 'jszakmeister/vim-togglecursor'
endif

Plug 'junegunn/goyo.vim', {'on' : 'Goyo'}
" End Vanity stuff"}}}

" Snippets and dictionaries"{{{
Plug 'vim-scripts/UltiSnips' | Plug 'jamescarr/snipmate-nodejs' | Plug 'bonsaiben/bootstrap-snippets', { 'for' :  'html' }  | Plug 'honza/vim-snippets'
" End Snippets and dictionaries"}}}

" Codify"{{{
Plug 'tpope/vim-unimpaired'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'godlygeek/tabular'
Plug 'mattn/emmet-vim', { 'for' : 'html' }
Plug 'kana/vim-smartinput'
Plug 'Valloric/MatchTagAlways'
" End Codify"}}}

" File Navigation"{{{
Plug 'kien/ctrlp.vim'
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
" En File Navigation"}}}

" @TODO  "{{{
Plug 'tpope/vim-abolish'
Plug 'scrooloose/syntastic'
Plug 'kana/vim-textobj-user'
" End of TODO}}}

Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'othree/html5.vim', { 'for' : 'html'}
Plug 'wincent/ferret', { 'on' : ['Ack', 'Acks']}
Plug 'peterhoeg/vim-qml', { 'for' : 'qml'}


function! DoRemote(arg)
  UpdateRemotePlugins
endfunction

"rails
Plug 'tpope/vim-rails' | Plug 'tpope/vim-bundler'  | Plug 'tpope/vim-abolish' |Plug 'tpope/vim-abolish' | Plug 'vim-scripts/dbext.vim' |  Plug 'tpope/vim-rake'
Plug 'tpope/vim-endwise'

"Latex
Plug 'xuhdev/vim-latex-live-preview'

" local bundle
" Mainly for plugins dev and 
" plugin I m testing and did not adopt yet.
if filereadable(expand("~/.bundle_local.vim")) 
    source '~/.bundle_local.vim'
endif

call plug#end()

if filereadable(expand("~/.local_vimrc"))
   source ~/.vimrc_local
endif
  
