#!/bin/bash
#
ret=`which lyx`
[[  $ret=="0" ]] && echo "lyx already installed"; exit 0

sudo apt-get install texlive-font-utils texlive-fonts-recommended inkscape -y
sudo apt-get install libtiff-tools noweb sgmltools-lite linuxdoc-tools -y 
sudo apt-get install writer2latex latex2rtf etoolbox lyx-dbg -y
sudo apt-get install texlive texlive-generic-extra texlive-latex-extra biber -y
sudo apt-get install lyx -y
