#! /bin/bash


#sudo apt-get remove ruby
#sudo apt-get autoremove
#exec $SHELL

sudo apt-get update
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev
libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties
libffi-dev -y
sudo apt-get update


cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc_local
echo 'eval "$(rbenv init -)"' >> ~/.zshrc_local
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.zshrc_local
exec $SHELL

rbenv install 2.3.1
rbenv global 2.3.1
ruby -v

exec $SHELL
gem install bundler 
rbenv rehash
exec $SHELL 
gem install rails -v 4.2.6
exec $SHELL 

