#!/bin/bash


ret=`which vim`
[[  $ret=="0" ]] && echo "Vim already installed"; exit 0

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim +PlugInstall +PlugClean! +qall

