source ~/dotfiles/zsh/lib/path.zsh
source ~/dotfiles/zsh/lib/functions.zsh
source ~/dotfiles/zsh/lib/aliases.zsh
source ~/dotfiles/zsh/lib/options.zsh
source ~/dotfiles/zsh/lib/completion.zsh
source ~/dotfiles/zsh/lib/keys.zsh
source ~/dotfiles/zsh/lib/prompt.zsh
source ~/dotfiles/zsh/lib/plugin/mvn/mvn.plugin.zsh

[ -f ~/.zshrc_local ] && . ~/.zshrc_local
[ -f ~/.fzf.zsh ]     && . ~/.fzf.zsh

