ZSH_DIR=${0:a:h}
PLUGINS_DIR="/lib/plugin"
FUNCTIONS_DIR="/lib/functions"
COMPL_DIR="/lib/compl"
CONFIGS_DIR="/lib/configs"
ZSH_DIR_PLUGINS="${ZSH_DIR}${PLUGINS_DIR}"
ZSH_DIR_FUNCTIONS="${ZSH_DIR}${FUNCTIONS_DIR}"
ZSH_DIR_COMPLETIONS="${ZSH_DIR}${COMPL_DIR}"
ZSH_DIR_CONFIGS="${ZSH_DIR}${CONFIGS_DIR}"

export CLICOLOR=1
# awesome cd movements from zshkit
setopt autocd autopushd pushdminus pushdsilent pushdtohome cdablevars
DIRSTACKSIZE=5


fpath=($ZSH_DIR_FUNCTIONS $ZSH_DIR_COMPLETIONS $fpath)
for func  ($ZSH_DIR_FUNCTIONS/*)
do
    foo=${func##*/}
    autoload $foo
done

#Prompt
source $ZSH_DIR/lib/prompt/zshrc.sh

# completion
autoload -U compinit
compinit

#Add plugins 
for plugin  ($ZSH_DIR_PLUGINS/*)
do
    fpath=($plugin $fpath)
done

for plugin  ($ZSH_DIR_PLUGINS/*)
do
    for plugin_int  ($plugin/*)
    do
        if [[ ${plugin_int##*/} =~ ".plugin.zsh" ]]
        then
            source $plugin_int
        fi 
    done
done

#load configs
for config  ($ZSH_DIR_CONFIGS/*)
do
    source $config
done


   fzf-dmenu() { 
    	# note: xdg-open has a bug with .desktop files, so we cant use that shit
    	selected="$(ls /usr/share/applications | fzf -e)"
    	nohup `grep '^Exec' "/usr/share/applications/$selected" | tail -1 | sed 's/^Exec=//' | sed 's/%.//'` >/dev/null 2>&1&
    }

    # hotkey to run the function (Ctrl+O)
    bindkey -s '^O' "fzf-dmenu\n"
